/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUIs;

import Database.CajeroController;
import java.awt.Font;
import javax.swing.JOptionPane;

/**
 *
 * @author a.jimenezg.2017
 */
public class CambiarPIN extends javax.swing.JPanel {
    private int numeroCuenta;
    private Cajero cajero;
    private CajeroController controller;
    /**
     * Creates new form CambiarPIN
     */
    public CambiarPIN(Cajero cajero,int cuenta) {
        initComponents();
        this.setSize(1000, 600);
        this.cajero = cajero;
        this.numeroCuenta = cuenta;
        this.controller = cajero.getController();
        
        //Fuentes
        Font Consolas12 = new java.awt.Font("Consolas", 0, 12);
        Font Consolas16 = new java.awt.Font("Consolas", 0, 16);
        
        jLabel1.setFont(Consolas16);
        jLabel1.setText("Cambiar PIN");
        
        jLabel2.setFont(Consolas12);
        jLabel2.setText("PIN actual");
        jTextField1.setFont(Consolas12);
        
        jLabel3.setFont(Consolas12);
        jLabel3.setText("Nuevo PIN");
        jTextField2.setFont(Consolas12);
        
        jLabel4.setFont(Consolas12);
        jLabel4.setText("Confirmar nuevo PIN");
        jTextField3.setFont(Consolas12);
        
        jButton1.setFont(Consolas12);
        jButton1.setText("Aceptar");
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jPanel11 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jPanel16 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jPanel17 = new javax.swing.JPanel();
        jPanel21 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jPanel32 = new javax.swing.JPanel();

        setLayout(new java.awt.GridLayout(3, 1));

        jPanel1.setLayout(new java.awt.GridLayout(3, 1));

        jLabel1.setText("jLabel1");
        jPanel4.add(jLabel1);

        jPanel1.add(jPanel4);
        jPanel1.add(jPanel5);

        jPanel6.setLayout(new java.awt.GridLayout(1, 0));
        jPanel1.add(jPanel6);

        add(jPanel1);

        jPanel2.setLayout(new java.awt.GridLayout(3, 1));

        jLabel2.setText("jLabel2");
        jPanel7.add(jLabel2);

        jTextField1.setMinimumSize(new java.awt.Dimension(100, 24));
        jTextField1.setPreferredSize(new java.awt.Dimension(100, 24));
        jPanel7.add(jTextField1);

        jPanel2.add(jPanel7);

        jLabel3.setText("jLabel2");
        jPanel11.add(jLabel3);

        jTextField2.setMinimumSize(new java.awt.Dimension(100, 24));
        jTextField2.setPreferredSize(new java.awt.Dimension(100, 24));
        jPanel11.add(jTextField2);

        jPanel2.add(jPanel11);

        jLabel4.setText("jLabel2");
        jPanel16.add(jLabel4);

        jTextField3.setMinimumSize(new java.awt.Dimension(100, 24));
        jTextField3.setPreferredSize(new java.awt.Dimension(100, 24));
        jPanel16.add(jTextField3);

        jPanel2.add(jPanel16);

        add(jPanel2);

        jPanel3.setLayout(new java.awt.GridLayout(3, 1));

        jPanel17.setLayout(new java.awt.GridLayout(3, 1));
        jPanel3.add(jPanel17);

        jButton1.setText("jButton1");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButton1MousePressed(evt);
            }
        });
        jPanel21.add(jButton1);

        jPanel3.add(jPanel21);

        jPanel32.setLayout(new java.awt.GridLayout(1, 0));
        jPanel3.add(jPanel32);

        add(jPanel3);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MousePressed
        if(this.controller.getPin(numeroCuenta) == Integer.parseInt(jTextField1.getText())){
            if(jTextField2.getText().equals(jTextField3.getText())){
                if(this.controller.isPINUnique(Integer.parseInt(jTextField3.getText()))){
                    this.controller.setPin(numeroCuenta, Integer.parseInt(jTextField3.getText()));            
                    this.setVisible(false);
                    cajero.activarOtraOperacion();
                } else JOptionPane.showMessageDialog(this, "Este PIN ya existe.");
            } else JOptionPane.showMessageDialog(this, "Los campos no coinciden.");
        } else JOptionPane.showMessageDialog(this, "PIN incorrecto.");
        
            
    }//GEN-LAST:event_jButton1MousePressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel21;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel32;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    // End of variables declaration//GEN-END:variables
}
