/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUIs;

import Database.CajeroController;
import Scripts.Cuenta;
import java.awt.Font;
import java.awt.event.ActionEvent;

/**
 *
 * @author d.mestanza.2017
 */
public class MenuPrincipal extends javax.swing.JPanel{
    private Cajero cajero;
    private CajeroController controller;
    int boton = 0;
    /**
     * Creates new form MenuPrincipal
     */
    public MenuPrincipal(Cajero cajero) {
        initComponents();
        this.setSize(1000, 600);
        this.cajero = cajero;
        this.controller = cajero.getController();
        
        
        //Fuentes
        Font Consolas12 = new java.awt.Font("Consolas", 0, 12);
        Font Consolas16 = new java.awt.Font("Consolas", 0, 16);

        jLabel9.setFont(Consolas16);
        jLabel9.setText("Selecciona una opción");

        jLabel1.setFont(Consolas12);
        jLabel1.setText("Ingresar dinero");
        jButton1.setFont(Consolas12);
        jButton1.setText("1");

        jLabel10.setFont(Consolas12);
        jLabel10.setText("Retirar dinero");
        jButton2.setFont(Consolas12);
        jButton2.setText("2");

        jLabel11.setFont(Consolas12);
        jLabel11.setText("Transacciones");
        jButton3.setFont(Consolas12);
        jButton3.setText("3");

        jLabel12.setFont(Consolas12);
        jLabel12.setText("Movimientos");
        jButton4.setFont(Consolas12);
        jButton4.setText("4");

        jLabel13.setFont(Consolas12);
        jLabel13.setText("Pagos");
        jButton5.setFont(Consolas12);
        jButton5.setText("5");

        jLabel14.setFont(Consolas12);
        jLabel14.setText("Cambiar PIN");
        jButton6.setFont(Consolas12);
        jButton6.setText("6");

        jLabel15.setFont(Consolas12);
        jLabel15.setText("Recargar teléfono");
        jButton7.setFont(Consolas12);
        jButton7.setText("7");

        jLabel16.setFont(Consolas12);
        jLabel16.setText("Sacar tarjeta");
        jButton8.setFont(Consolas12);
        jButton8.setText("8");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel15 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jPanel16 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jPanel17 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jPanel18 = new javax.swing.JPanel();
        jPanel19 = new javax.swing.JPanel();
        jPanel20 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jPanel21 = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        jPanel22 = new javax.swing.JPanel();
        jPanel23 = new javax.swing.JPanel();
        jButton4 = new javax.swing.JButton();
        jPanel24 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jPanel25 = new javax.swing.JPanel();
        jPanel26 = new javax.swing.JPanel();
        jPanel27 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jPanel28 = new javax.swing.JPanel();
        jButton5 = new javax.swing.JButton();
        jPanel29 = new javax.swing.JPanel();
        jPanel30 = new javax.swing.JPanel();
        jButton6 = new javax.swing.JButton();
        jPanel31 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jPanel32 = new javax.swing.JPanel();
        jPanel33 = new javax.swing.JPanel();
        jPanel34 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jPanel35 = new javax.swing.JPanel();
        jButton7 = new javax.swing.JButton();
        jPanel36 = new javax.swing.JPanel();
        jPanel37 = new javax.swing.JPanel();
        jButton8 = new javax.swing.JButton();
        jPanel38 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(1000, 600));
        setLayout(new java.awt.GridLayout(5, 0));

        jPanel1.add(jLabel9);

        add(jPanel1);

        jPanel2.setLayout(new java.awt.GridLayout(1, 0));

        jPanel6.setLayout(new java.awt.GridLayout(1, 0));
        jPanel8.add(jLabel1);

        jPanel6.add(jPanel8);
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButton1MousePressed(evt);
            }
        });
        jPanel15.add(jButton1);

        jPanel6.add(jPanel15);

        jPanel2.add(jPanel6);

        jPanel7.setLayout(new java.awt.GridLayout(1, 0));

        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButton2MousePressed(evt);
            }
        });
        jPanel16.add(jButton2);

        jPanel7.add(jPanel16);

        jPanel17.add(jLabel10);

        jPanel7.add(jPanel17);

        jPanel2.add(jPanel7);

        add(jPanel2);

        jPanel18.setLayout(new java.awt.GridLayout(1, 0));

        jPanel19.setLayout(new java.awt.GridLayout(1, 0));

        jPanel20.add(jLabel11);

        jPanel19.add(jPanel20);

        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButton3MousePressed(evt);
            }
        });
        jPanel21.add(jButton3);

        jPanel19.add(jPanel21);

        jPanel18.add(jPanel19);

        jPanel22.setLayout(new java.awt.GridLayout(1, 0));

        jButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButton4MousePressed(evt);
            }
        });
        jPanel23.add(jButton4);

        jPanel22.add(jPanel23);

        jPanel24.add(jLabel12);

        jPanel22.add(jPanel24);

        jPanel18.add(jPanel22);

        add(jPanel18);

        jPanel25.setLayout(new java.awt.GridLayout(1, 0));

        jPanel26.setLayout(new java.awt.GridLayout(1, 0));

        jPanel27.add(jLabel13);

        jPanel26.add(jPanel27);

        jButton5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButton5MousePressed(evt);
            }
        });
        jPanel28.add(jButton5);

        jPanel26.add(jPanel28);

        jPanel25.add(jPanel26);

        jPanel29.setLayout(new java.awt.GridLayout(1, 0));

        jButton6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButton6MousePressed(evt);
            }
        });
        jPanel30.add(jButton6);

        jPanel29.add(jPanel30);

        jPanel31.add(jLabel14);

        jPanel29.add(jPanel31);

        jPanel25.add(jPanel29);

        add(jPanel25);

        jPanel32.setLayout(new java.awt.GridLayout(1, 0));

        jPanel33.setLayout(new java.awt.GridLayout(1, 0));

        jPanel34.add(jLabel15);

        jPanel33.add(jPanel34);

        jButton7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButton7MousePressed(evt);
            }
        });
        jPanel35.add(jButton7);

        jPanel33.add(jPanel35);

        jPanel32.add(jPanel33);

        jPanel36.setLayout(new java.awt.GridLayout(1, 0));

        jButton8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButton8MousePressed(evt);
            }
        });
        jPanel37.add(jButton8);

        jPanel36.add(jPanel37);

        jPanel38.add(jLabel16);

        jPanel36.add(jPanel38);

        jPanel32.add(jPanel36);

        add(jPanel32);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MousePressed
        this.setVisible(false);
        boton = 1;
        cajero.elegirSubmenu(boton);
    }//GEN-LAST:event_jButton1MousePressed

    private void jButton2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MousePressed
        this.setVisible(false);
        boton = 2;
        cajero.elegirSubmenu(boton);
    }//GEN-LAST:event_jButton2MousePressed

    private void jButton3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MousePressed
        this.setVisible(false);
        boton = 3;
        cajero.elegirSubmenu(boton);
    }//GEN-LAST:event_jButton3MousePressed

    private void jButton4MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MousePressed
        this.setVisible(false);
        boton = 4;
        cajero.elegirSubmenu(boton);
    }//GEN-LAST:event_jButton4MousePressed

    private void jButton5MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton5MousePressed
        this.setVisible(false);
        boton = 5;
        cajero.elegirSubmenu(boton);
    }//GEN-LAST:event_jButton5MousePressed

    private void jButton6MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton6MousePressed
        this.setVisible(false);
        boton = 6;
        cajero.elegirSubmenu(boton);
    }//GEN-LAST:event_jButton6MousePressed

    private void jButton7MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton7MousePressed
        this.setVisible(false);
        boton = 7;
        cajero.elegirSubmenu(boton);
    }//GEN-LAST:event_jButton7MousePressed

    private void jButton8MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton8MousePressed
        this.setVisible(false);
        boton = 8;
        cajero.elegirSubmenu(boton);
    }//GEN-LAST:event_jButton8MousePressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel20;
    private javax.swing.JPanel jPanel21;
    private javax.swing.JPanel jPanel22;
    private javax.swing.JPanel jPanel23;
    private javax.swing.JPanel jPanel24;
    private javax.swing.JPanel jPanel25;
    private javax.swing.JPanel jPanel26;
    private javax.swing.JPanel jPanel27;
    private javax.swing.JPanel jPanel28;
    private javax.swing.JPanel jPanel29;
    private javax.swing.JPanel jPanel30;
    private javax.swing.JPanel jPanel31;
    private javax.swing.JPanel jPanel32;
    private javax.swing.JPanel jPanel33;
    private javax.swing.JPanel jPanel34;
    private javax.swing.JPanel jPanel35;
    private javax.swing.JPanel jPanel36;
    private javax.swing.JPanel jPanel37;
    private javax.swing.JPanel jPanel38;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    // End of variables declaration//GEN-END:variables
}
