/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUIs;

/**
 *
 * @author a.jimenezg.2017
 */
public class Transacciones extends javax.swing.JPanel {
    Cajero cajero;
    /**
     * Creates new form Transacciones
     */
    public Transacciones(Cajero cajero) {
        initComponents();
        this.setSize(1000, 600);
        this.cajero = cajero;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jPanel9 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jPanel10 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jPanel16 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel17 = new javax.swing.JPanel();
        jPanel21 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jPanel32 = new javax.swing.JPanel();

        setLayout(new java.awt.GridLayout(3, 1));

        jPanel1.setLayout(new java.awt.GridLayout(3, 1));

        jPanel4.setLayout(new java.awt.GridLayout(3, 1));
        jPanel1.add(jPanel4);

        jLabel1.setText("jLabel1");
        jPanel5.add(jLabel1);

        jPanel1.add(jPanel5);

        jPanel6.setLayout(new java.awt.GridLayout());
        jPanel1.add(jPanel6);

        add(jPanel1);

        jPanel2.setLayout(new java.awt.GridLayout(3, 1));

        jPanel7.setLayout(new java.awt.GridLayout(3, 1));
        jPanel2.add(jPanel7);

        jPanel11.setLayout(new java.awt.GridLayout(1, 3));

        jLabel2.setText("jLabel2");
        jPanel8.add(jLabel2);

        jTextField1.setText("jTextField1");
        jPanel8.add(jTextField1);

        jPanel11.add(jPanel8);

        jLabel3.setText("jLabel3");
        jPanel9.add(jLabel3);

        jTextField2.setText("jTextField2");
        jPanel9.add(jTextField2);

        jPanel11.add(jPanel9);

        jLabel4.setText("jLabel4");
        jPanel10.add(jLabel4);

        jTextField3.setText("jTextField3");
        jPanel10.add(jTextField3);

        jPanel11.add(jPanel10);

        jPanel2.add(jPanel11);

        jPanel16.setLayout(new java.awt.GridLayout());
        jPanel2.add(jPanel16);

        add(jPanel2);

        jPanel3.setLayout(new java.awt.GridLayout(3, 1));

        jPanel17.setLayout(new java.awt.GridLayout(3, 1));
        jPanel3.add(jPanel17);

        jButton1.setText("jButton1");
        jPanel21.add(jButton1);

        jPanel3.add(jPanel21);

        jPanel32.setLayout(new java.awt.GridLayout());
        jPanel3.add(jPanel32);

        add(jPanel3);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel21;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel32;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    // End of variables declaration//GEN-END:variables
}
